name: Deploy static portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if your branch is called master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # use . if your index.html is in the root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
